- hosts: prometheus
  remote_user: lanmiix
  become: yes
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  remote_user: lanmiix
  become: yes
  become_method: sudo
  roles:
    - grafana
